name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  elixir:
    name: OTP ${{matrix.pair.otp_version}} / Elixir ${{matrix.pair.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pair:
              elixir: '1.12'
              otp: '24.3'
          - pair:
              elixir: '1.19'
              otp: '28.4'
            lint: lint
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Run mix deps.get
        run: mix deps.get

      - name: Run mix format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run mix deps.compile
        run: mix deps.compile

      - name: Run mix compile
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run mix dialyzer
        run: mix dialyzer
        if: ${{ matrix.lint }}

      - name: Run mix test
        run: mix test
