name: Publish Package

on:
  push:
    branches:
      - master

env:
  elixir: '1.19'
  otp: '28.4'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124
        with:
          otp-version: ${{env.otp}}
          elixir-version: ${{env.elixir}}
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{env.elixir}}-${{env.otp}}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{env.elixir}}-${{env.otp}}-
      - name: Run mix deps.get
        run: mix deps.get
      - name: Publish package to hex.pm
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
